language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
- echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
install:
- mvn -s .travis.maven.settings.xml -version -B
script:
- mvn -s .travis.maven.settings.xml clean install
- mvn -s .travis.maven.settings.xml deploy -P release
notifications:
  slack:
    secure: Pp8PFtR6GrrzmX553FFBaCs6GbFvhJAFJOFsvoAKKwQxmeVHLXJpNh1TQADIBrdu7PUGY0uRna9OeMUb8mO6f8x4rDKy2t/UVGsmpBIqLFcnSvzDSlrM7dUQJnmsulJLdGNKxpk6JxQVeNrdAfCffdz9CUuTf087HzyiakZEFO1/U9sShMDjjUkrCLU9pUJBhfLz2g5JD1Qv3+raJHHD2f+hpwgyBy9+rlMuchywWNMZ2qI1mkFDJ8z4GMzqAwQrTPi3nPQV6Nhu0iv0r/vbkNs9a0OLusL8rsuJNXpvGS4+L6el030/PHirIHEbuNyZfrAfathboBNNdtzDL2bOFLz7naKMh4LCWk7GzA/o8LkQ31APj/YuAQcUHyUTzWyCi/aUoUXFuUF29tf0gTRzOLnmJZcFr1SkoaaDJ/CeswstDh74iWzfuPwTMykIbpdBnr5QoXKEAp/+ruDHJWm4gyeL1HbaONy2gW6bY2rv6Zhr7i24flCUXLIC18j0XtYY9sVKwe6jFhfSGCDVK0TkGulFKSwucJ/gMlwtaxWZrOgqrlQ5j/QXagF9VomPlt81Y9K1SHx01lH03Rg6bNwN78d6nbyQ13zzweOJEo2acDRqxIkx7jCGePWOIhBYLjbuVpYEcRML/pcKgvfTia50837JEJpU4d7yMBKVeB/4H+8=
    
