language: java

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

## export GPG details
before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
    - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
    
install:
  - mvn -s .travis.maven.settings.xml -version -B

script:
  - mvn -s .travis.maven.settings.xml clean install
